### ISSUE TITLE
The MD5 values of all files in the new version are different from those in the old version.

### ISSUE THREAD

**Issue by JerryLiew** [preyneyv/league-vcs#1]
i have backed up the version of 11.23 to 11.24, but this tool copyed all files,then i found the MD5 of  any file in new version is different from old version, even they have same size and file version. What the hell happened?

**Comment by preyneyv** [comment]
Hmm, that's really strange. Has it worked successfully for you in the past? Can you also post a copy of `patches/11.23.something.json` and `patches/11.24.something.json`?

**Comment by JerryLiew** [comment]
[11.23.409.567.txt](https://github.com/preyneyv/league-vcs/files/7738899/11.23.409.567.txt)
[11.24.412.2185.txt](https://github.com/preyneyv/league-vcs/files/7738900/11.24.412.2185.txt)
i compare files between old and new version byte by byte,and found that many champions data file only one byte which index from the file header is 4 has changed.Maybe the first four bytes  indicate the verison of the file?

**Comment by JerryLiew** [comment]
[11.23.409.567.txt](https://github.com/preyneyv/league-vcs/files/7738899/11.23.409.567.txt)
[11.24.412.2185.txt](https://github.com/preyneyv/league-vcs/files/7738900/11.24.412.2185.txt)
i compare files between old and new version byte by byte,and found that many champions data file only one byte which index from the file header is 4 has changed.Maybe the first four bytes  indicate the verison of the file?

**Comment by preyneyv** [comment]
Yeah, that would definitely count as enough of a change to make it re-index those files. As for what those bytes represent, it's really hard to say. If you could follow up on this in a week or so when the new patch comes out, I'd very much appreciate that.

**Comment by JerryLiew** [comment]
I've done some research between 11.23 and 11.24,and found that all files whose name end with ".wad.client" have same four-bytes header in a patch. Also, different patch have different header, even if the file has not changed.It was the header cause the changes in MD5.so, i rewrited a tool to sovle this problem by ignoring the first four bytes of those file when i compute MD5 value and save the header in patch file, and also resotre the header when restore the patch. My ultimate goal is make a intergration into the replaybook, mybe you know this tool. but more tests are necessary before that.

**Comment by preyneyv** [comment]
One thing I think you should check before doing that is making sure that the files are still cross-compatible. i.e., you should check that you can use the unchanged .wad.client from 11.23 with the 11.24 game executable.

**Comment by JerryLiew** [comment]
Yeah, but whether compatible or not,i no longer need to copy those files. But the problem is that even if you do, there are still many files that need to be copied so that I only save 3-4GB storage space.The chinese version of lol take 13.8GB space.Maybe I need to do more research to optimize the space occupation.But it's almost impossible.   :grin:

**Comment by preyneyv** [comment]
Oh right because you also have to have both language files... I experimented with compression early on in the project (https://github.com/preyneyv/large-vcs/blob/master/large_vcs/__init__.py#L36-L55), but it makes adding a patch slow, and also takes longer to restore a patch, since it has to decompress and duplicate the file. 

Right now, restoring a patch is done by creating hardlinks to all the files so you don't end up with two copies of them, which is way faster. If you compress it, then you _have_ to decompress it before you can use it, so you'll definitely need the copies.

If you're interested in pursuing the idea further though, maybe you could think of some form of archive system, where files that weren't used in the last 3 patches (for instance) will be compressed. That way, you'd have a balance between repository size and file loading speed.

One thing I wanted to add but never did get around to is putting an upper limit on the overall size and dropping the oldest patches once that limit is hit.

**Comment by JerryLiew** [comment]
Thank you for these good idea, I learned from your practice and copied files through hard links. in addidtion, I have tried to compress those files with compression software. but the compression ratio is so high,  maybe RIOT has already compressed it.What is the compression ratio when you compress those?

> 哦，对，因为您还必须同时拥有两种语言文件......我在项目早期尝试了压缩（[https://github.com/preyneyv/large-vcs/blob/master/large_vcs/__init__.py#L36- L55](https://github.com/preyneyv/large-vcs/blob/master/large_vcs/__init__.py#L36-L55)），但它会使添加补丁变慢，并且恢复补丁也需要更长的时间，因为它必须解压缩和复制文件。
> 
> 现在，恢复补丁是通过为所有文件创建硬链接来完成的，这样你就不会得到它们的两个副本，这要快得多。如果您压缩它，那么您_必须_先解压缩它才能使用它，因此您肯定需要副本。
> 
> 如果您有兴趣进一步探索这个想法，也许您可​​以考虑某种形式的存档系统，其中将压缩最近 3 个补丁中未使用的文件（例如）。这样，您就可以在存储库大小和文件加载速度之间取得平衡。
> 
> 我想添加但从未考虑过的一件事是对整体大小设置上限，并在达到该限制后删除最旧的补丁。

thanks,but the provided url is invalid.

**Comment by preyneyv** [comment]
Oh, sorry about that, the repo was marked private (not sure why). I've just changed the permissions, you should be able to see it now. Regarding compression, I tried using the `zlib` package to do it. I don't recall how effective it was, so you'll have to try it out and see for yourself.

https://docs.python.org/3/library/zlib.html#zlib.compressobj

**Comment by JerryLiew** [comment]
ok, in my research ,compressing files is not worth it,all those ".wad.client" files has been already compressed by riot.

**Comment by preyneyv** [comment]
Yeah, that makes sense I suppose.
