### ISSUE TITLE
Unable to open League VCS. cx_Freeze Python error in main script

### ISSUE THREAD

**Issue by ShadowHazel** [preyneyv/league-vcs#2]
I can't open league vs normally or as admin and all log files are blank.
![image](https://user-images.githubusercontent.com/47856331/180653531-b47cb584-0c80-4ee7-a784-9a66aba0ee7d.png)

**Comment by ShadowHazel** [comment]
Oh I found the issue. user_settings.json was corrupted and was filled with just "null" repeated several times. Deleting the file fixed it.

**Comment by preyneyv** [comment]
Sorry I missed this! Glad you figured it out!
